name: ci

on:
  push:
    branches:
      - 'main'
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Client Docker
        uses: docker/build-push-action@v3
        with:
          context: client
          file: client/Dockerfile.dev
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react-test:latest
      -
        name: Client Test
        uses: docker/build-push-action@v3
        with:
          context: client
          file: client/Dockerfile.dev
          run: docker run -e CI=true ${{ secrets.DOCKER_HUB_USERNAME }}/react-test npm test
      -
        name: Build and push Client
        uses: docker/build-push-action@v3
        with:
          context: client
          file: client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/multi-client:latest
      -
        name: Build and push Nginx
        uses: docker/build-push-action@v3
        with:
          context: nginx
          file: nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/multi-nginx:latest
      -
        name: Build and push Server
        uses: docker/build-push-action@v3
        with:
          context: server
          file: server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/multi-server:latest
      -
        name: Build and push Worker
        uses: docker/build-push-action@v3
        with:
          context: worker
          file: worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/multi-worker:latest
